"""empty message

Revision ID: 00e27235a2fb
Revises: 
Create Date: 2018-11-19 16:13:17.313165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e27235a2fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=160), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('menuOne_id', sa.Integer(), nullable=True),
    sa.Column('menuTwo_id', sa.Integer(), nullable=True),
    sa.Column('menuThree_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menuOne_id'], ['menu.id'], ),
    sa.ForeignKeyConstraint(['menuThree_id'], ['menu.id'], ),
    sa.ForeignKeyConstraint(['menuTwo_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_table('user')
    op.drop_table('menu')
    # ### end Alembic commands ###
