"""empty message

Revision ID: dbc505e9f8e9
Revises: 
Create Date: 2018-11-29 14:13:13.634960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbc505e9f8e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('menuOne_fn', sa.String(length=128), nullable=True),
    sa.Column('menuThree_fn', sa.String(length=128), nullable=True),
    sa.Column('menuTwo_fn', sa.String(length=128), nullable=True),
    sa.Column('filePath', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['menuOne_fn'], ['user.username'], ),
    sa.ForeignKeyConstraint(['menuThree_fn'], ['user.username'], ),
    sa.ForeignKeyConstraint(['menuTwo_fn'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
